server:
  port: 8889
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: compose
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxc_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #  pgsql 配置信息
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/compose

  messages:
    encoding: UTF-8

  #数据库版本管理配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/flyway
#mybatis
mybatis-plus:
  mapper-locations: "classpath*:mapper/**/*Mapper.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


swagger:
  #是否显示swagger页面
  show: true
  #swagger接口扫描地址
  base-package: com.wsm.compose.compose_api;com.wsm.compose.compose_shiro



logging:
  path: log/
